# Generated by Django 2.2 on 2021-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='parking_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
