# Generated by Django 2.2 on 2021-09-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartPark', '0002_alter_parking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
